### ISSUE TITLE
Sanitize Unit Tests

### ISSUE THREAD

**Issue by deas** [pink-gorilla/notebook-encoding#4]
- Use dedicated test repo instead of sample-notebooks
- Use external config (like creds.edn) to set target repo/gists (other devs forking?)

**Comment by awb99** [comment]
sample notebooks is pretty much done. therefore rename sample-notebooks to unittest-notebooks

**Comment by awb99** [comment]
sample-notebooks renamed to unittest-notebooks
https://github.com/pink-gorilla/unittest-notebooks
